import { CAMPAIGN_OBJECTIVES, CAMPAIGN_PHASES, CAMPAIGN_STRATEGIES, DEBATE_TOPICS, ELECTION_MODELS } from '../data/simulation/campaign-rules.js?v=20260926-1';
import { affiliationOf, markForPerson } from './person-marks.js?v=20260926-1';
import { campaignActivities, campaignSummary, strategyFit, strategyOf } from '../core/campaign-engine.js?v=20260926-1';
import { resultDescription } from '../core/election-engine.js?v=20260926-1';
import { formatDate } from '../core/time.js?v=20260926-1';
import { careerLevelLabel } from '../data/regions.js?v=20260926-1';
import { upcomingElections } from '../core/career-engine.js?v=20260926-1';
import { renderElectionReport } from './election-report.js?v=20260926-1';
import { glyph } from './visuals.js?v=20260926-1';

const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const roleLabels={sindaco:'Candidatura a sindaco',consigliere:'Candidato in lista per il consiglio',presidente:'Candidato alla presidenza regionale',deputato:'Candidato alla Camera',senatore:'Candidato al Senato',uninominale:'Collegio uninominale simulato',eurodeputato:'Candidato al Parlamento europeo'};
const ROLE_OPTIONS={comunale:[['sindaco','Sindaco'],['consigliere','Consigliere']],regionale:[['presidente','Presidente di Regione'],['consigliere','Consigliere regionale']],politiche:[['deputato','Deputato (lista)'],['senatore','Senatore (lista)'],['uninominale','Collegio uninominale']],europee:[['eurodeputato','Eurodeputato']]};
const number=value=>new Intl.NumberFormat('it-IT').format(Math.round(Number(value)||0));
const pct=value=>`${Number(value??0).toLocaleString('it-IT',{maximumFractionDigits:1})}%`;
const partyName=party=>party?.officialName??party?.name??'Indipendente';
const partyDescription=party=>party?.source==='real'?party.factualDescription:party?.description;
// Documented people show only verified identity data; their campaign numbers remain simulated.
const realIdentity=candidate=>candidate?.realReference?`Deputato in carica${candidate.realReference.groupName?` · ${candidate.realReference.groupName}`:''}${candidate.realReference.electedOnList?` · eletto nel 2022 nella lista ${candidate.realReference.electedOnList}`:''}`:null;
const realSourceLink=candidate=>candidate?.realReference?.sourceUrl?`<a class="text-link" href="${esc(candidate.realReference.sourceUrl)}" target="_blank" rel="noopener noreferrer">Scheda ufficiale ↗</a>`:'';
const sourceText=source=>source==='real'?'Dato reale verificato':source==='user'?'Creato da te':'Dato simulato';
const COST_NAMES={volunteers:'vol.',organization:'org.',politicalCapital:'cap. politico'};
const activityCost=activity=>Object.entries(activity.cost).filter(([,value])=>value).map(([name,value])=>`${name==='money'?`€${number(value)}`:`${value} ${COST_NAMES[name]??name}`}`).join(' · ')||'Nessun costo diretto';
const CATEGORY_GROUPS=[['territory','Territorio e porta a porta','pin'],['event','Eventi e comizi','megaphone'],['media','Media, social e confronti','media'],['ads','Pubblicità e affissioni','news'],['internal','Partito, lista e alleanze','users'],['resources','Fondi','money']];
const SCOPE_NAMES={internal:'Partito',media:'Media',debate:'Confronto',national:'Tutto il territorio',broad:'Tutto il territorio',focused:'Area scelta',rival:'Contro un avversario',any:'Risorse'};
const factorLabel=value=>value>=1.05?`×${String(Math.round(value*100)/100).replace('.',',')}`:value<=.95?`×${String(Math.round(value*100)/100).replace('.',',')}`:'';

export function renderCampaignPage(state,parties=[],logoFor=()=>null) {
  const campaign=state.campaign;
  if(!state.career?.playerId)return `<div class="campaign-empty"><p class="campaign-kicker">PREPARA UNA SFIDA</p><h2>Prima crea il tuo politico</h2><p>La carriera serve per definire territorio, partito e punto di partenza.</p><button class="primary-button" data-action="new-career">Crea il politico</button></div>`;
  if(!campaign||campaign.status==='finished')return campaign?.status==='finished'?renderResult(campaign,parties,logoFor,state):renderSetup(state,parties,logoFor);
  return renderActive(campaign,parties,logoFor);
}

function strategyCards(selected='consolidare',name='campaign-strategy') {
  return `<div class="campaign-strategies" role="radiogroup" aria-label="Strategia della campagna">${Object.entries(CAMPAIGN_STRATEGIES).map(([id,item])=>`<label class="campaign-strategy ${selected===id?'is-selected':''}"><input type="radio" name="${name}" value="${id}" ${selected===id?'checked':''} data-campaign-strategy-choice /><span class="campaign-strategy-icon">${glyph(item.icon,16)}</span><span><strong>${esc(item.label)}</strong><small>${esc(item.detail)}</small><em class="pros">+ ${esc(item.pros)}</em><em class="cons">− ${esc(item.cons)}</em></span></label>`).join('')}</div>`;
}

function renderSetup(state,parties,logoFor) {
  const player=state.dataset.politicians.find(item=>item.id===state.career.playerId);
  const party=parties.find(item=>item.id===(player?.partyId??state.career.partyId));
  const logo=party&&logoFor(party)?`<img class="campaign-party-logo" src="${esc(logoFor(party))}" alt="${esc(party.logoAlt??`Logo ${partyName(party)}`)}">`:'';
  const partyCard=party?`<div class="campaign-party-identity">${logo}<div><small>${sourceText(party.source)}</small><strong>${esc(partyName(party))}${party.abbreviation?` · ${esc(party.abbreviation)}`:''}</strong><span>${esc(partyDescription(party)||'La scheda mostra solo le informazioni documentate.')}</span>${party.website?`<a href="${esc(party.website)}" target="_blank" rel="noopener noreferrer">Sito ufficiale ↗</a>`:''}</div><button class="text-link" data-party-profile="${esc(party.id)}">Scheda del partito ↗</button></div>`:`<div class="campaign-party-identity"><div><small>APPARTENENZA</small><strong>Indipendente</strong><span>La campagna parte senza lista di partito.</span></div></div>`;
  const open=state.game?upcomingElections(state.game).filter(item=>item.status==='open'):[];
  const type=open[0]?.type??'comunale';
  const openList=open.length?`<div class="campaign-open-list">${open.map(item=>`<div class="campaign-open"><strong>${esc(item.label)}</strong><small>Candidature fino al ${esc(formatDate(item.windowClosesAt))} · voto il ${esc(formatDate(item.electionDate))}</small></div>`).join('')}</div>`:`<p class="campaign-real-note">Nessuna finestra di candidatura è aperta ora: puoi preparare la campagna e partire quando si apre (vedi il calendario nella Panoramica).</p>`;
  return `<section class="campaign-intro"><div><span class="campaign-kicker">PREPARAZIONE ELETTORALE</span><h2>Ogni campagna è una scelta di priorità.</h2><p>Scegli elezione, ruolo, obiettivo e strategia. Tempo, risorse e consenso sono simulati sul territorio; nessuna strategia vince sempre e l’esito non è mai scritto in anticipo.</p></div><div class="campaign-source-note"><strong>Scenario di gioco</strong><span>Le proiezioni non sono sondaggi né previsioni ufficiali. Dati delle organizzazioni reali restano separati dalle variabili simulate.</span></div></section>
  <section class="campaign-setup"><div class="campaign-section-head"><div><span class="campaign-kicker">LA SFIDA</span><h3>Imposta la campagna</h3></div><time>${esc(formatDate(state.clock.currentDate))}</time></div>${openList}<div class="campaign-setup-grid"><label>Tipo di elezione<select data-campaign-setup="electionType">${Object.keys(ROLE_OPTIONS).map(id=>`<option value="${id}" ${id===type?'selected':''}>${esc(ELECTION_MODELS[id].label)}${open.some(item=>item.type===id)?' · candidature aperte':''}</option>`).join('')}</select></label><label>Obiettivo<select data-campaign-setup="objective">${Object.entries(CAMPAIGN_OBJECTIVES).map(([id,item])=>`<option value="${id}" ${id==='build'?'selected':''}>${esc(item.label)}</option>`).join('')}</select></label><label>Ruolo in candidatura<select data-campaign-setup="role">${(ROLE_OPTIONS[type]??ROLE_OPTIONS.comunale).map(([id,label])=>`<option value="${id}">${esc(label)}</option>`).join('')}</select></label><label class="municipality-band-field" ${type==='comunale'?'':'hidden'}>Dimensione del comune<select data-campaign-setup="municipalityBand"><option value="fino-15000">Fino a 15.000 abitanti</option><option value="oltre-15000">Oltre 15.000 abitanti</option></select></label><label>Tema (per la strategia sui temi)<select data-campaign-setup="topicId">${DEBATE_TOPICS.map(topic=>`<option value="${topic.id}">${esc(topic.label)}</option>`).join('')}</select></label></div><p class="campaign-model-help" data-campaign-model-help>${esc(ELECTION_MODELS[type].strategy)} · <a href="${esc(ELECTION_MODELS[type].referenceUrl)}" target="_blank" rel="noopener noreferrer">${esc(ELECTION_MODELS[type].referenceName)} ↗</a></p>
  <div class="campaign-setup-strategy"><span class="campaign-kicker">STRATEGIA ELETTORALE</span><p class="campaign-real-note">La strategia cambia cosa rende di più, quanto rischi e quanto può oscillare il risultato. Si può cambiare durante la campagna, a un costo.</p>${strategyCards('consolidare')}</div>
  <div class="campaign-setup-party"><span class="campaign-kicker">PARTITO E CANDIDATURA</span>${partyCard}${party&&party.source!=='user'?`<p class="campaign-real-note">La candidatura in un partito esistente parte come <strong>da negoziare</strong>: superare la soglia di sostegno interno la rende probabile, non certa. Riunioni e costruzione della lista aumentano le probabilità; la ricandidatura parlamentare non è garantita.</p>`:''}</div><div class="campaign-setup-bottom"><div><strong>La tua base:</strong> ${esc(player?.municipality??'')} · ${esc(player?.region??'')}<span> · ${esc(careerLevelLabel(state.career.currentLevel??state.career.initialLevel)??'')}</span></div><button class="primary-button" data-action="campaign-start">Inizia la campagna →</button></div></section>
  <section class="campaign-method"><strong>Modelli distinti</strong><span>Comunale: comune, premio di maggioranza e possibile ballottaggio.</span><span>Regionale: aree della regione e premio al vincitore.</span><span>Politiche: collegi, liste bloccate e soglia del 3%.</span><span>Europee: circoscrizioni, preferenze e soglia del 4%.</span></section>`;
}

function phaseStrip(campaign,summary) {
  const phases=campaign.stage==='ballottaggio'?['ballottaggio']:['apertura','centrale','finale'];
  return `<section class="campaign-phases" aria-label="Fasi della campagna">${phases.map(id=>`<div class="campaign-phase ${summary.phase===id?'is-current':''} ${phases.indexOf(id)<phases.indexOf(summary.phase)?'is-done':''}"><strong>${esc(CAMPAIGN_PHASES[id].label)}</strong><small>${esc(CAMPAIGN_PHASES[id].detail)}</small></div>`).join('')}</section>`;
}
function strategyPanel(campaign) {
  const strategy=strategyOf(campaign);
  const fit=strategy.id?strategyFit(campaign,strategy.id):1;
  const target=campaign.candidates.find(item=>item.id===campaign.strategy?.targetId);
  const topic=DEBATE_TOPICS.find(item=>item.id===campaign.strategy?.topicId);
  const rivals=campaign.candidates.filter(item=>!item.isPlayer&&item.status==='active');
  const locked=campaign.totalDays-campaign.day<=5;
  return `<section class="campaign-block campaign-strategy-panel"><div class="campaign-section-head"><div><span class="campaign-kicker">STRATEGIA</span><h3>${esc(strategy.label)}${topic?` · ${esc(topic.label)}`:''}${target?` · contro ${esc(target.realReference?.fullName??'una candidatura simulata')}`:''}</h3></div><span class="campaign-fit ${fit>=1.05?'good':fit<=.92?'bad':''}">${fit>=1.05?'Adatta al momento':fit<=.92?'Poco adatta al momento':'Neutra al momento'} · ${String(Math.round(fit*100)/100).replace('.',',')}</span></div>${strategy.id?`<p class="campaign-strategy-copy"><em class="pros">+ ${esc(strategy.pros)}</em><em class="cons">− ${esc(strategy.cons)}</em></p>`:'<p class="campaign-strategy-copy">Nessuna strategia dichiarata: ogni attività rende il suo valore base.</p>'}
    <details class="campaign-strategy-change"><summary>${strategy.id?'Cambia strategia (2 capitale politico, un po’ di credibilità)':'Scegli una strategia'}</summary>${strategyCards(strategy.id??'consolidare','campaign-strategy-live')}<div class="campaign-activity-controls"><label>Tema<select data-campaign-strategy-topic>${DEBATE_TOPICS.map(item=>`<option value="${item.id}" ${item.id===(campaign.strategy?.topicId??campaign.nationalContext.salientTopic)?'selected':''}>${esc(item.label)}${item.id===campaign.nationalContext.salientTopic?' · al centro del dibattito':''}</option>`).join('')}</select></label><label>Avversario da contrastare<select data-campaign-strategy-target>${rivals.map(item=>`<option value="${esc(item.id)}" ${item.id===campaign.strategy?.targetId?'selected':''}>${esc(item.realReference?.fullName??item.displayName)}</option>`).join('')}</select></label><button class="secondary-button" data-campaign-strategy-apply ${locked?'disabled':''}>${locked?'Negli ultimi 5 giorni non si cambia':'Applica la strategia'}</button></div></details></section>`;
}

function renderActive(campaign,parties,logoFor) {
  const summary=campaignSummary(campaign);
  const player=campaign.candidates.find(item=>item.isPlayer);
  const party=parties.find(item=>item.id===campaign.partyId);
  const days=summary.daysRemaining;
  const weeks=Math.floor(days/7), remainder=days%7;
  const nomination=campaign.nomination.status==='pending'?`Sostegno interno: ${campaign.nomination.internalSupport}/10 · candidatura da confermare entro ${campaign.nomination.deadlineDay} giorni.`:campaign.nomination.status==='excluded'?'Escluso dalla candidatura del partito.':'Candidatura confermata.';
  const resources=[['Fondi simulati',`€${number(player.resources.money)}`],['Volontari',number(player.resources.volunteers)],['Organizzazione',`${number(player.resources.organization)}/100`],['Visibilità',`${number(campaign.resources.visibility)}/100`],['Capitale politico',number(player.resources.politicalCapital)]];
  const historyPoints=campaign.consensusHistory.map(item=>Number(item.value));
  const historyMin=Math.min(...historyPoints,0); const historyMax=Math.max(...historyPoints,10);
  const spark=historyPoints.map((value,index)=>`${historyPoints.length<=1?4:index*92/(historyPoints.length-1)+4},${27-(value-historyMin)/(historyMax-historyMin||1)*21}`).join(' ');
  const areas=summary.territories.map(area=>`<div class="campaign-area-row"><div><strong>${esc(area.name)}</strong><small>${number(area.weight)}% del peso · andamento ${area.localTrend>.35?'favorevole':area.localTrend<-.35?'in calo':'stabile'} · ${area.consensus>25?'forte presenza':area.consensus<11?'da recuperare':'area contendibile'}</small></div><strong>${pct(area.consensus)}</strong><div class="campaign-meter"><i style="width:${Math.max(3,area.consensus)}%"></i></div></div>`).join('');
  const rivals=campaign.candidates.filter(item=>!item.isPlayer).map(candidate=>{
    const affiliated=parties.find(item=>item.id===candidate.partyId);
    const support=summary.territories.reduce((sum,area)=>sum+Number(campaign.territories.find(t=>t.id===area.id)?.supportByCandidate[candidate.id]??0)*area.weight,0)/100;
    const img=affiliated&&logoFor(affiliated)?`<img src="${esc(logoFor(affiliated))}" alt="${esc(affiliated.logoAlt??`Logo ${partyName(affiliated)}`)}">`:'';
    const affiliation=realIdentity(candidate)??(affiliated?partyName(affiliated):'Indipendente simulato');
    const initials=candidate.realReference?candidate.realReference.fullName.split(/\s+/).map(word=>word[0]).join('').slice(0,2):(affiliated?.abbreviation??'S').slice(0,2);
    const realMark=candidate.realReference&&affiliationOf(candidate.realReference.politicianId)?markForPerson(candidate.realReference.politicianId):'';
    const targeted=campaign.strategy?.id==='contrasto'&&campaign.strategy.targetId===candidate.id;
    return `<div class="campaign-rival ${candidate.status==='allied'?'is-allied':''} ${candidate.realReference?'is-real':''} ${targeted?'is-target':''}"><div class="campaign-rival-logo">${realMark||img||esc(initials)}</div><div class="campaign-rival-main"><strong>${candidate.realReference?esc(candidate.realReference.fullName):'Candidatura simulata'}${targeted?' <em>nel mirino</em>':''}</strong><span>${esc(affiliation)}${!candidate.realReference&&affiliated?.abbreviation?` · ${esc(affiliated.abbreviation)}`:''}</span><small>${candidate.realReference?'Persona reale · dati di campagna simulati · ':''}${esc(candidate.lastAction)}</small>${realSourceLink(candidate)}</div><div class="campaign-rival-score"><strong>${pct(support)}</strong><span>${candidate.status==='allied'?'in alleanza':`risorse ${number(candidate.resources.money)} €`}</span></div>${affiliated?`<button class="text-link" data-party-profile="${esc(affiliated.id)}">Scheda partito ↗</button>`:''}</div>`;
  }).join('');
  const territoryOptions=campaign.territories.map(area=>`<option value="${esc(area.id)}" ${area.id===campaign.candidacy?.territoryId?'selected':''}>${esc(area.name)}</option>`).join('');
  const debateOptions=DEBATE_TOPICS.map(topic=>`<option value="${topic.id}" ${topic.id===(campaign.strategy?.topicId??campaign.nationalContext.salientTopic)?'selected':''}>${esc(topic.label)} · preparazione ${number(campaign.preparationByTopic[topic.id]??0)}${topic.id===campaign.nationalContext.salientTopic?' · al centro del dibattito':''}</option>`).join('');
  const allyOptions=campaign.candidates.filter(item=>!item.isPlayer&&item.status==='active').map(candidate=>{const affiliated=parties.find(item=>item.id===candidate.partyId);return `<option value="${esc(candidate.id)}">${candidate.realReference?esc(candidate.realReference.fullName):`Candidatura simulata · ${esc(affiliated?partyName(affiliated):'indipendente')}`}</option>`;}).join('');
  const strategy=strategyOf(campaign);
  const list=campaignActivities(campaign);
  const activityGroups=CATEGORY_GROUPS.map(([category,label,icon])=>{
    const rows=list.filter(item=>item.activity.category===category);
    if(!rows.length)return '';
    const available=rows.filter(item=>item.ok).length;
    const body=rows.map(({activity,ok,reason,modifiers,expected})=>{
      const chips=[['Fase',modifiers.phase],['Elezione',modifiers.type],['Strategia',modifiers.strategy],['Ripetizione',modifiers.repetition],['Tema',modifiers.topic],['Clima',modifiers.mood],['Partito',modifiers.party],['Area',modifiers.area]].filter(([,value])=>factorLabel(value)).map(([name,value])=>`<i class="${value>1?'up':'down'}">${esc(name)} ${factorLabel(value)}</i>`).join('');
      const risk=Math.round(activity.risk*(strategy.risk??1));
      return `<div class="campaign-activity ${ok?'':'is-blocked'}"><div class="campaign-activity-copy"><strong>${esc(activity.label)}</strong><span>${esc(activity.detail)}</span><small>${activity.days} ${activity.days===1?'giorno':'giorni'} · Rischio ${risk}/100 · ${esc(SCOPE_NAMES[activity.scope]??'Territorio')}${expected?` · effetto atteso <b>+${String(expected).replace('.',',')} punti</b>`:''}</small>${chips?`<span class="campaign-mods">${chips}</span>`:''}</div><div class="campaign-activity-cost">${esc(activityCost(activity))}</div><button class="campaign-action-button" data-campaign-activity="${activity.id}" ${ok?'':'disabled'}>${ok?'Scegli':'Non disponibile'}</button>${reason?`<small class="campaign-activity-reason">${esc(reason)}</small>`:''}</div>`;
    }).join('');
    return `<details class="campaign-activity-group" data-remember="campagna-${category}" ${['territory','media','event'].includes(category)?'open':''}><summary>${glyph(icon,16)}<span>${esc(label)}</span><small>${available} disponibili su ${rows.length}</small></summary>${body}</details>`;
  }).join('');
  const pending=campaign.pendingEvents.map(event=>`<article class="campaign-event-choice"><span class="campaign-kicker">EVENTO · ${esc(formatDate(event.date,{day:'numeric',month:'short'}))}</span><h4>${esc(event.title)}</h4><p>${esc(event.body)}</p><div>${event.choices.map(choice=>`<button class="secondary-button" data-campaign-event="${esc(event.id)}" data-campaign-choice="${esc(choice.id)}">${esc(choice.label)}</button>`).join('')}</div></article>`).join('');
  const history=campaign.history.slice(0,6).map(item=>`<div class="campaign-log-row"><time>G${item.day}</time><div><strong>${esc(item.text)}</strong><small>${esc(formatDate(item.date,{day:'numeric',month:'short'}))} · simulazione</small></div></div>`).join('');
  const activeAlliances=campaign.alliances.filter(item=>item.status==='active').map(alliance=>{const counterpart=campaign.candidates.find(item=>item.id===alliance.partnerCandidateId);const affiliated=parties.find(item=>item.id===counterpart?.partyId);const own=alliance.leaderCandidateId===campaign.playerCandidateId;return `<div class="campaign-alliance-row"><span>↔</span><div><strong>${esc(own?(counterpart?.realReference?.fullName??(affiliated?partyName(affiliated):'Candidatura simulata')):'Accordo fra altre candidature')}</strong><small>${esc(alliance.terms)}${alliance.transfer?` · ${Math.round(alliance.transfer*100)}% dei voti segue l’accordo`:''}</small></div>${own?`<button class="secondary-button" data-campaign-break-alliance="${esc(alliance.id)}">Interrompi</button>`:''}</div>`;}).join('');
  const internalRivals=campaign.internalCandidates.map(item=>`<span>${esc(item.displayName)} · ${number(item.internalSupport)}/10</span>`).join('');
  const nominationPanel=campaign.nomination.status==='pending'?`<div class="campaign-nomination ${campaign.nomination.incumbent?'is-incumbent':''}"><div><strong>${campaign.nomination.incumbent?'Ricandidatura da negoziare':'Candidatura da ottenere'}</strong><span>${esc(nomination)} La competizione interna può cambiare prima della scadenza; superare la soglia rende la candidatura probabile, non certa.</span></div>${internalRivals?`<div class="campaign-internal-rivals"><small>CONCORRENTI INTERNI SIMULATI</small>${internalRivals}</div>`:''}</div>`:`<div class="campaign-nomination is-approved"><strong>${campaign.nomination.status==='excluded'?'Candidatura esclusa':'Candidatura confermata'}</strong><span>${esc(nomination)}${campaign.nomination.decision?.lowerPlace?` In lista al posto ${campaign.candidacy.listPosition}: meno di quanto speravi.`:''}</span></div>`;
  const crisis=campaign.crisis?`<section class="campaign-crisis" role="status">${glyph('scandal',18)}<div><strong>Polemica in corso: ${esc(campaign.crisis.title)}</strong><span>Ogni settimana costa consenso e reputazione finché non la gestisci (o si spegne da sola dopo tre settimane).</span></div><button class="secondary-button" data-campaign-activity="crisis_response">Gestisci la crisi</button></section>`:'';
  return `<section class="campaign-active-head"><div><span class="campaign-kicker">CAMPAGNA · ${esc(campaign.electionLabel.toUpperCase())}</span><h2>${esc(player.displayName)}</h2><p>${esc(roleLabels[campaign.candidacy.role]??campaign.candidacy.role)} · ${esc(party?partyName(party):'Indipendente')} · ${esc(campaign.territories[0]?.name??'Italia')}</p></div><div class="campaign-countdown"><small>AL VOTO</small><strong>${days}<span>giorni</span></strong><time>${esc(formatDate(campaign.electionDate))}</time></div></section>
  ${phaseStrip(campaign,summary)}
  <section class="campaign-goal-line"><div><small>OBIETTIVO</small><strong>${esc(CAMPAIGN_OBJECTIVES[campaign.objective]?.label??'Costruire una base')}</strong></div><div><small>POSIZIONE NELLO SCENARIO</small><strong>${pct(summary.consensus)} <span>${summary.playerPosition?`${summary.playerPosition}ª posizione`:'consenso simulato'}</span></strong></div><div><small>CANDIDATURA</small><strong>${campaign.nomination.status==='approved'?'Confermata':campaign.nomination.status==='excluded'?'Esclusa':'Da conquistare'}</strong></div><div><small>PROSSIMA FASE</small><strong>${campaign.stage==='ballottaggio'?'Ballottaggio':`Settimana ${weeks+1}${remainder?` · ${remainder} gg`:''}`}</strong></div></section>
  ${crisis}
  ${pending?`<section class="campaign-event-list">${pending}</section>`:''}
  ${nominationPanel}
  ${strategyPanel(campaign)}
  <section class="campaign-resource-line" aria-label="Risorse della campagna">${resources.map(([label,value])=>`<div><small>${label}</small><strong>${value}</strong></div>`).join('')}</section>
  <section class="campaign-consensus-trend"><div><small>ANDAMENTO DEL CONSENSO NELLA CAMPAGNA</small><strong>${pct(summary.consensus)}</strong><span>${campaign.consensusHistory.length>1?`variazione ${campaign.consensusHistory.at(-1).value>=campaign.consensusHistory[0].value?'+':''}${(campaign.consensusHistory.at(-1).value-campaign.consensusHistory[0].value).toFixed(1).replace('.',',')} punti dallo scenario iniziale`:'scenario appena avviato'}${summary.expectation!==null?` · attesa iniziale ${pct(summary.expectation)}`:''} · proiezione simulata, non sondaggio</span></div><svg viewBox="0 0 100 30" preserveAspectRatio="none" aria-label="Andamento storico simulato"><polyline points="${spark}" /></svg></section>
  <div class="campaign-columns"><section class="campaign-block campaign-territories"><div class="campaign-section-head"><div><span class="campaign-kicker">GEOGRAFIA DEL VOTO</span><h3>Dove sei forte</h3></div><small>Clima nazionale simulato ${number(campaign.nationalContext.moodIndex)}/100 · ${campaign.nationalContext.macroTrend>0?'tendenza favorevole':campaign.nationalContext.macroTrend<0?'contesto in calo':'contesto stabile'} · tema: ${esc(DEBATE_TOPICS.find(topic=>topic.id===campaign.nationalContext.salientTopic)?.label??'scenario politico')}</small></div>${areas}<p class="campaign-footnote">La percentuale è una proiezione interna dello scenario e non deriva da un sondaggio. <button class="text-link" data-nav="sondaggi">Aggancio sondaggi: non collegato →</button></p></section>
  <section class="campaign-block campaign-opponents"><div class="campaign-section-head"><div><span class="campaign-kicker">CONTENDENTI</span><h3>Le altre campagne</h3></div><small>${number(campaign.aiTurns)} turni di campagna simulati</small></div>${rivals||'<p>Nessuna candidatura simulata disponibile.</p>'}${activeAlliances?`<div class="campaign-alliance-list"><span class="campaign-kicker">ACCORDI ATTIVI</span>${activeAlliances}</div>`:''}<div class="campaign-opponent-note">Le candidature avversarie sono simulate. Se mostrano un partito reale, il legame è un riferimento d’identità; le percentuali e le strategie sono generate dal gioco.</div></section></div>
  <section class="campaign-block campaign-activities"><div class="campaign-section-head"><div><span class="campaign-kicker">DECIDI COME IMPIEGARE LE RISORSE</span><h3>Attività di campagna</h3></div><small>Giorni, denaro, organizzazione e rischio sono limitati; l’effetto dipende da fase, elezione, strategia e ripetizione</small></div><div class="campaign-activity-controls"><label>Territorio<select data-campaign-territory>${territoryOptions}</select></label><label>Tema<select data-campaign-topic>${debateOptions}</select></label>${allyOptions?`<label>Avversario o possibile alleato<select data-campaign-ally>${allyOptions}</select></label>`:''}</div><div class="campaign-activity-groups">${activityGroups}</div></section>
  ${campaign.events.length?`<section class="campaign-block campaign-events-resolved"><div class="campaign-section-head"><div><span class="campaign-kicker">CRONACA DELLA CAMPAGNA</span><h3>Eventi già affrontati</h3></div></div>${campaign.events.slice(0,4).map(event=>`<div class="campaign-log-row"><time>${esc(formatDate(event.date,{day:'numeric',month:'short'}))}</time><div><strong>${esc(event.title)}</strong><small>${esc(event.choiceLabel)}${event.outcome?` · ${esc(event.outcome)}`:''} · dato simulato</small></div></div>`).join('')}</section>`:''}
  <section class="campaign-block campaign-history"><div class="campaign-section-head"><div><span class="campaign-kicker">TRACCIA DELLE DECISIONI</span><h3>Ultime mosse</h3></div><small>La partita viene salvata dopo ogni scelta</small></div>${history}</section>
  <footer class="campaign-rules-note"><span>Modello: ${esc(campaign.model)} · ${esc(sourceText('simulation'))}</span><span>Meccaniche elettorali semplificate per il gioco; <a href="${esc(ELECTION_MODELS[campaign.electionType]?.referenceUrl??'#')}" target="_blank" rel="noopener noreferrer">fonte istituzionale di riferimento ↗</a>. Non sostituiscono la normativa o un calcolo ufficiale.</span></footer>`;
}

function renderResult(campaign,parties,logoFor,state={}) {
  const result=campaign.result;
  const report=state.career?.lastElectionReport?.campaignId===campaign.id?state.career.lastElectionReport:null;
  return `<section class="campaign-result-head"><span class="campaign-kicker">SCRUTINIO CONCLUSO · RISULTATO SIMULATO</span><h2>${esc(result?.outcome?.label??(result?.objectiveMet?'Obiettivo raggiunto.':'La corsa è finita.'))}</h2><p>${esc(resultDescription(campaign,result))}${parliamentOutcome(campaign,state)?` ${esc(parliamentOutcome(campaign,state))}`:''}</p></section>
  ${report?renderElectionReport(report):`<p class="campaign-real-note">Percentuale ${pct(result?.playerShare??0)} · seggi ${number(result?.playerSeats??0)} · mandato ${result?.personalMandate?'sì':'no'}.</p>`}
  <section class="campaign-block campaign-history"><div class="campaign-section-head"><div><span class="campaign-kicker">STORICO</span><h3>Chiusura della campagna</h3></div><time>${esc(formatDate(campaign.closedAt))}</time></div>${campaign.history.slice(0,8).map(item=>`<div class="campaign-log-row"><time>G${item.day}</time><div><strong>${esc(item.text)}</strong><small>${esc(formatDate(item.date,{day:'numeric',month:'short'}))} · simulazione</small></div></div>`).join('')}</section><div class="campaign-result-actions"><span>Il risultato e l’impatto sulla carriera sono salvati in questo browser.</span>${state.career?.parliamentContext&&campaign.electionType==='politiche'&&result?.personalMandate?'<button class="secondary-button" data-nav="parlamento">Vai al Parlamento</button>':''}<button class="primary-button" data-action="campaign-new">Prepara una nuova elezione</button></div><footer class="campaign-rules-note"><span>Modello: ${esc(result?.model??campaign.model)} · ${esc(sourceText('simulation'))}</span><span>Le cifre sono prodotte dal motore di gioco, non sono risultati reali; soglia UE del 4% da fonte verificata. <a href="${esc(ELECTION_MODELS[campaign.electionType]?.referenceUrl??'#')}" target="_blank" rel="noopener noreferrer">Riferimento istituzionale ↗</a></span></footer>`;
}

function parliamentOutcome(campaign,state) {
  if(campaign.electionType!=='politiche') return '';
  if(campaign.result?.personalMandate&&state.career?.parliamentContext) return state.career.parliamentContext.groupId?'Il mandato parlamentare prosegue con il tuo gruppo.':'Mandato parlamentare ottenuto: scegli il gruppo nella sezione Parlamento.';
  if(campaign.candidacy.incumbent&&!campaign.result?.personalMandate) return 'Il seggio non è stato confermato: il mandato parlamentare si conclude e le proposte in esame decadono.';
  return '';
}
