// The full report of a vote, shared by the electoral centre and the campaign page.
import { formatDate } from '../core/time.js?v=20260926-1';
import { glyph } from './visuals.js?v=20260926-1';
import { arrow, badge, bar, card, empty, esc, kpi, num, pct, signed, table } from './sections-kit.js?v=20260926-1';

const EVENT_LABELS = { 'dopo-voto-vittoria': 'Le prime mosse dopo il voto', 'dopo-voto-sconfitta': 'Come ripartire dopo il voto', 'giunta-offerta': 'La giunta valuta il tuo nome', 'giunta-composizione': 'La scelta della tua giunta', 'capogruppo-opposizione': 'Chi guida l’opposizione', 'ricorso-elettorale': 'Un possibile ricorso', 'resa-dei-conti': 'Resa dei conti nel partito', 'consultazioni-governo': 'La squadra di governo', 'impegni-elettorali': 'Gli impegni presi in campagna' };
const STAT_NAMES = { reputation: 'Reputazione', influence: 'Influenza', notoriety: 'Notorietà', popularity: 'Popolarità' };
const toneOf = value => value > 0 ? 'good' : value < 0 ? 'bad' : 'neutral';

// The full report of a vote: outcome, numbers, territory, runoff and what it changes for the career.
export function renderElectionReport(report, { compact = false } = {}) {
  if (!report) return empty('Nessun risultato ancora: il resoconto completo comparirà qui dopo il primo voto.');
  const outcome = report.outcome ?? {};
  const tone = outcome.tone === 'good' ? 'good' : outcome.tone === 'neutral' ? 'warn' : 'bad';
  const personal = [];
  if (outcome.preference) personal.push(kpi({ label: 'Preferenze', value: num(outcome.preference.votes, 0), note: `${outcome.preference.rank}º nella lista su ${outcome.preference.listCandidates} · seggi della lista ${outcome.preference.seats}` }));
  if (outcome.district) personal.push(kpi({ label: 'Collegio uninominale', value: outcome.district.position ? `${outcome.district.position}º posto` : '—', note: `${esc(outcome.district.name ?? '')} · ${pct(outcome.district.share)}${outcome.district.position === 1 ? ` · margine ${num(outcome.district.margin)} punti` : ''}`, tone: outcome.district.position === 1 ? 'good' : 'bad' }));
  if (outcome.constituency) personal.push(kpi({ label: 'Seggi nella tua circoscrizione', value: num(outcome.constituency.seats, 0), note: `${esc(outcome.constituency.name ?? '')} · lista bloccata: conta la posizione` }));
  if (outcome.threshold) personal.push(kpi({ label: 'Soglia di sbarramento', value: `${num(outcome.threshold)}%`, tone: outcome.belowThreshold ? 'bad' : 'good', note: outcome.belowThreshold ? 'non superata: nessun seggio' : 'superata' }));
  const groups = (report.groups ?? []).map((row, index) => ({ _class: row.player ? 'is-player' : '', pos: `${index + 1}ª`, name: `<strong>${esc(row.label)}</strong>${row.partyIds?.length > 1 ? ` <small>${row.partyIds.length} liste in accordo</small>` : ''}`, share: `<span class="eh-share"><b>${pct(row.percent)}</b>${bar(row.percent, row.player ? 'good' : '')}</span>`, votes: num(row.votes, 0), seats: num(row.seats, 0), runoff: row.runoffPercent !== null && row.runoffPercent !== undefined ? pct(row.runoffPercent) : '—' }));
  const hasRunoff = (report.runoff ?? []).length > 0;
  const territories = (report.territories ?? []).map(area => ({ area: `<strong>${esc(area.name)}</strong>`, share: `<span class="eh-share"><b>${pct(area.percent)}</b>${bar(area.percent, area.position === 1 ? 'good' : '')}</span>`, position: area.position ? `${area.position}ª` : '—', winner: area.position === 1 ? '<span class="tone-good">Tu</span>' : `${esc(area.winner ?? '—')} ${area.winnerPercent !== null ? `(${pct(area.winnerPercent)})` : ''}` }));
  const consequences = report.consequences ?? {};
  const statChips = Object.entries(consequences.stats ?? {}).filter(([, value]) => value).map(([metric, value]) => `<li class="tone-${toneOf(value)}"><span>${esc(STAT_NAMES[metric] ?? metric)}</span><b>${signed(value)}</b></li>`).join('');
  const partyChips = consequences.party ? `<li class="tone-${toneOf(consequences.party.support)}"><span>Sostegno nel partito</span><b>${signed(consequences.party.support)}</b></li><li class="tone-${toneOf(consequences.party.leadership)}"><span>Rapporto con la leadership</span><b>${signed(consequences.party.leadership)}</b></li>${consequences.party.currents ? `<li class="tone-${toneOf(consequences.party.currents.aligned)}"><span>La tua area interna</span><b>${signed(consequences.party.currents.aligned)}</b></li><li class="tone-${toneOf(consequences.party.currents.others)}"><span>Le altre aree</span><b>${signed(consequences.party.currents.others)}</b></li>` : ''}` : '';
  const capital = consequences.capital ? `<li class="tone-${toneOf(consequences.capital)}"><span>Capitale politico</span><b>${signed(consequences.capital, 0)}</b></li>` : '';
  const office = consequences.office ? `<div class="eh-office">${glyph('star', 18)}<span><strong>${esc(consequences.office.title)}</strong><small>${consequences.office.side === 'maggioranza' ? 'In maggioranza' : consequences.office.side === 'opposizione' ? 'All’opposizione' : 'Nuovo mandato'}${consequences.office.via ? ` · ${esc({ diretto: 'eletto direttamente', ballottaggio: 'eletto al ballottaggio', lista: 'eletto con la lista', coalizione: 'eletto grazie alla coalizione', proporzionale: 'eletto nel proporzionale', collegio: 'eletto nel collegio', opposizione: 'seggio da candidato sconfitto' }[consequences.office.via] ?? consequences.office.via)}` : ''}</small></span></div>` : `<div class="eh-office is-none">${glyph('route', 18)}<span><strong>Nessun nuovo incarico</strong><small>La carriera continua: il risultato resta nella memoria politica e prepara la prossima occasione.</small></span></div>`;
  const nextMoves = (consequences.events ?? []).map(id => `<li>${glyph('clock', 14)}<span>${esc(EVENT_LABELS[id] ?? id)}</span></li>`).join('');
  return `<div class="eh-report">
    <section class="eh-result-hero tone-${tone}"><div><span class="section-kicker">SCRUTINIO · ${esc(report.electionLabel ?? report.electionType ?? '')} · ${esc(formatDate(report.date))} · RISULTATO SIMULATO</span><h3>${esc(outcome.label ?? (report.personalMandate ? 'Eletto' : 'Non eletto'))}</h3><p>${esc(outcome.positionLabel ?? '')}${outcome.margin !== null && outcome.margin !== undefined ? ` · ${outcome.margin >= 0 ? `vantaggio di ${num(outcome.margin)} punti sul secondo` : `${num(Math.abs(outcome.margin))} punti dal primo`}` : ''}</p></div><div class="eh-result-badges">${badge(outcome.expectationLabel ?? 'In linea con le attese', outcome.expectation === 'sopra' ? 'good' : outcome.expectation === 'sotto' ? 'bad' : 'neutral')}${report.personalMandate ? badge('Mandato conquistato', 'good') : badge('Nessun mandato', 'bad')}</div></section>
    <div class="sx-kpis eh-score">${kpi({ label: 'Voti', value: num(report.playerVotes, 0), note: 'su 100.000 schede simulate' })}${kpi({ label: hasRunoff ? 'Voto al ballottaggio' : 'Percentuale', value: pct(report.playerShare) })}${kpi({ label: 'Posizione', value: outcome.position ? `${outcome.position}ª` : '—' })}${kpi({ label: 'Seggi della lista', value: num(report.playerSeats, 0) })}${kpi({ label: 'Affluenza', value: report.turnout ? pct(report.turnout) : '—' })}${kpi({ label: 'Attese e sondaggi', value: outcome.expected !== null && outcome.expected !== undefined ? pct(outcome.expected) : '—', note: `${report.pollShare !== null && report.pollShare !== undefined ? `sondaggio del partito ${pct(report.pollShare)} · ` : ''}scarto ${signed((hasRunoff ? (report.groups ?? []).find(row => row.player)?.percent ?? report.playerShare : report.playerShare) - (outcome.expected ?? report.playerShare))} punti` })}</div>
    ${personal.length ? `<div class="sx-kpis eh-personal">${personal.join('')}</div>` : ''}
    ${compact ? '' : `<div class="sx-grid two">
      ${card({ kicker: 'LISTE E COALIZIONI', title: 'Il risultato', body: table([['pos', 'Pos.'], ['name', 'Lista o candidatura'], ['share', '%', 'num'], ['votes', 'Voti', 'num'], ['seats', 'Seggi', 'num'], ...(hasRunoff ? [['runoff', 'Ballottaggio', 'num']] : [])], groups) })}
      ${card({ kicker: 'DISTRIBUZIONE TERRITORIALE', title: 'Dove hai preso i voti', body: table([['area', 'Area'], ['share', 'Il tuo voto', 'num'], ['position', 'Pos.', 'num'], ['winner', 'Primo']], territories) })}
    </div>`}
    <div class="sx-grid two">
      ${card({ kicker: 'CONSEGUENZE SULLA CARRIERA', title: 'Cosa cambia', body: `${office}<ul class="eh-deltas">${statChips}${capital}${partyChips}</ul>${(consequences.lines ?? []).length ? `<ul class="eh-lines">${consequences.lines.map(line => `<li>${esc(line)}</li>`).join('')}</ul>` : ''}${consequences.government ? `<p class="sx-note">${glyph('ministry', 14)} ${esc(consequences.government)}</p>` : ''}` })}
      ${card({ kicker: 'PROSSIME MOSSE', title: 'Cosa succede ora', body: `${nextMoves ? `<ul class="eh-next">${nextMoves}</ul><p class="sx-note">Le decisioni sono in agenda: nessuna è automatica, ognuna può andare bene o male.</p><button class="secondary-button" data-nav="calendario">Apri l’agenda ${arrow}</button>` : '<p class="sx-note">Nessuna decisione in sospeso.</p>'}${report.seatRule ? `<p class="sx-note">${esc(report.seatRule)}</p>` : ''}` })}
    </div>
  </div>`;
}

