import { realDatabase } from '../data/repositories/real-data.js?v=20260924-16';

const esc = (value = '') => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
const pageSize = 16;

export function renderLogoAdmin({ selectedId, query = '', page = 1, metadata = [], entities: providedEntities = null, logoFor = () => null, error = '', pendingPreview = null, pendingRemote = false, urlDraft = '', urlLoading = false } = {}) {
  const entities = [...(providedEntities ?? [...(realDatabase.parties ?? []), ...(realDatabase.politicalMovements ?? [])])].sort((a,b) => (a.officialName ?? a.name ?? '').localeCompare(b.officialName ?? b.name ?? '','it'));
  const metadataById = new Map(metadata.map(item => [item.partyId,item]));
  const normalizedQuery = query.trim().toLocaleLowerCase('it-IT');
  const matches = entities.filter(item => !normalizedQuery || `${item.officialName ?? item.name ?? ''} ${item.abbreviation ?? ''}`.toLocaleLowerCase('it-IT').includes(normalizedQuery));
  const visible = matches.slice(0,Math.max(1,Number(page)||1)*pageSize);
  const selected = entities.find(item => item.id === selectedId) ?? entities[0];
  const local = selected ? metadataById.get(selected.id) : null;
  const previewSrc = pendingPreview || (selected ? logoFor(selected) : null);
  const list = visible.map(item => {
    const info = metadataById.get(item.id);
    const hasLogo = Boolean(info || item.logoAsset || item.logoUrl);
    return `<button type="button" class="logo-admin-item ${selected?.id === item.id ? 'selected' : ''}" data-logo-party-id="${esc(item.id)}" aria-pressed="${selected?.id === item.id}"><span class="logo-admin-item-mark">${hasLogo ? '✓' : '—'}</span><span><strong>${esc(item.officialName ?? item.name ?? '')}</strong><small>${esc(item.abbreviation || (item.entityType === 'politicalMovement' ? 'Movimento politico' : 'Sigla non documentata'))}</small></span><em>${info ? (info.url ? 'Tuo · da indirizzo' : 'Tuo · file') : item.logoVerified ? 'Ufficiale verificato' : 'Da aggiungere'}</em></button>`;
  }).join('');
  const selectedHtml = selected ? `<section class="logo-admin-editor"><div class="logo-admin-selected"><div class="logo-admin-preview">${previewSrc ? `<img src="${esc(previewSrc)}" alt="${esc(local?.alt || selected.logoAlt || `Anteprima logo ${selected.officialName ?? selected.name ?? 'partito'}`)}" />` : '<span>Logo non disponibile</span>'}</div><div><span class="section-kicker">ID STABILE</span><code>${esc(selected.id)}</code><h2>${esc(selected.officialName ?? selected.name ?? '')}</h2><span>${selected.entityType === 'politicalMovement' ? 'Movimento politico' : selected.source === 'user' ? 'Partito creato da te' : selected.source === 'simulation' ? 'Partito della simulazione' : 'Partito'}</span></div></div>
    <div class="logo-origin">${selected.logoVerified ? `<span class="verified-badge">Logo ufficiale verificato nel repository</span>` : '<span class="source-pill">Nessun logo ufficiale verificato</span>'}${local ? `<span class="source-pill user-pill">In uso: logo aggiunto da te${local.url ? ' (indirizzo esterno)' : ' (file nel browser)'}</span>` : ''}</div>
    <div class="logo-admin-note"><strong>Loghi dell’utente, separati da quelli verificati</strong><span>Il logo che aggiungi si salva in questo browser e prevale nella tua partita; il logo ufficiale verificato resta invariato e torna visibile se elimini il tuo.</span></div>
    <form class="logo-url-form" data-logo-url-form><label class="logo-admin-field">Indirizzo dell’immagine (URL)<input type="url" name="url" data-logo-url inputmode="url" placeholder="https://…/logo.svg" value="${esc(urlDraft)}" autocomplete="off" /></label><button type="submit" class="secondary-button" ${urlLoading ? 'disabled' : ''}>${urlLoading ? 'Carico…' : 'Carica dall’indirizzo'}</button></form>
    <label class="logo-admin-upload">Oppure carica un file SVG, PNG, JPEG o WebP<input type="file" accept="image/svg+xml,image/png,image/jpeg,image/webp,.svg,.png,.jpg,.jpeg,.webp" data-logo-upload /></label>
    <label class="logo-admin-field">Fonte del logo<input type="url" data-logo-source placeholder="https://…" value="${esc((pendingRemote || pendingPreview) && urlDraft ? urlDraft : local?.source || selected.logoSource || '')}" /></label>
    <label class="logo-admin-field">Testo alternativo<input type="text" data-logo-alt maxlength="160" value="${esc(local?.alt || selected.logoAlt || `Logo di ${selected.officialName ?? selected.name ?? 'partito'}`)}" /></label>
    <label class="logo-admin-check"><input type="checkbox" data-logo-verified ${local?.verified ? 'checked' : ''} /><span>La fonte indicata è il sito ufficiale del partito (resta comunque un logo dell’utente)</span></label>
    ${selected.logoSource && !local ? `<a class="catalog-source" href="${esc(selected.logoSource)}" target="_blank" rel="noopener noreferrer">Apri fonte del logo esistente ↗</a>` : ''}
    <div class="logo-admin-preview-caption" data-logo-preview-caption>${pendingPreview ? (pendingRemote ? 'Anteprima dall’indirizzo. Il sito non permette di copiarla: verrà salvato l’indirizzo, visibile solo online.' : 'Anteprima temporanea. Premi “Salva nel browser” per conservarla, anche offline.') : local ? (local.url ? 'Logo collegato da un indirizzo esterno: visibile quando sei online.' : 'Logo salvato in questo browser: disponibile anche offline.') : selected.logoVerified ? 'Logo ufficiale incluso nel repository.' : 'Nessun logo disponibile: l’archivio userà un segnaposto neutro.'}</div>
    <div class="logo-admin-actions"><button type="button" class="primary-button" data-action="logo-save" ${pendingPreview ? '' : 'disabled'}>Salva nel browser</button><button type="button" class="secondary-button" data-action="logo-delete" ${local ? '' : 'disabled'}>Elimina il tuo logo</button></div>
    ${error ? `<div class="wizard-errors" role="alert">${esc(error)}</div>` : ''}<p class="catalog-footnote">La casella “verificata” descrive la provenienza dichiarata per questo file. Il pannello è locale e non è un sistema di autenticazione amministrativa.</p></section>` : '<div class="catalog-empty">Nessun partito disponibile.</div>';
  return `<div class="logo-admin-backdrop" data-logo-admin-backdrop><section class="logo-admin-dialog" role="dialog" aria-modal="true" aria-labelledby="logo-admin-title"><header class="logo-admin-heading"><div><span class="section-kicker">IMPOSTAZIONI · ASSET LOCALI</span><h1 id="logo-admin-title">Gestione loghi</h1><p>Pannello amministrativo locale, senza password simulata.</p></div><button type="button" class="profile-modal-close" data-action="logo-admin-close" aria-label="Chiudi">×</button></header><div class="logo-admin-toolbar"><label class="catalog-search"><span>Cerca partito o movimento</span><input type="search" data-logo-query value="${esc(query)}" placeholder="Nome o sigla…" autocomplete="off" /></label><div><button type="button" class="secondary-button" data-action="logo-export">Esporta configurazione</button><button type="button" class="secondary-button" data-action="logo-import">Importa</button><input type="file" accept="application/json,.json" data-logo-import-file hidden /></div></div><div class="logo-admin-layout"><nav class="logo-admin-list" aria-label="Partiti e movimenti">${list || '<div class="catalog-empty">Nessun risultato.</div>'}${visible.length < matches.length ? `<button type="button" class="logo-admin-more" data-action="logo-more">Mostra altri (${matches.length-visible.length})</button>` : ''}</nav>${selectedHtml}</div></section></div>`;
}
