import { realDatabase } from '../data/repositories/real-data.js?v=20260924-1';

const esc = (value = '') => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
const pageSize = 16;

export function renderLogoAdmin({ selectedId, query = '', page = 1, metadata = [], entities: providedEntities = null, logoFor = () => null, error = '', pendingPreview = null } = {}) {
  const entities = [...(providedEntities ?? [...(realDatabase.parties ?? []), ...(realDatabase.politicalMovements ?? [])])].sort((a,b) => (a.officialName ?? a.name ?? '').localeCompare(b.officialName ?? b.name ?? '','it'));
  const metadataById = new Map(metadata.map(item => [item.partyId,item]));
  const normalizedQuery = query.trim().toLocaleLowerCase('it-IT');
  const matches = entities.filter(item => !normalizedQuery || `${item.officialName ?? item.name ?? ''} ${item.abbreviation ?? ''}`.toLocaleLowerCase('it-IT').includes(normalizedQuery));
  const visible = matches.slice(0,Math.max(1,Number(page)||1)*pageSize);
  const selected = entities.find(item => item.id === selectedId) ?? entities[0];
  const local = selected ? metadataById.get(selected.id) : null;
  const previewSrc = pendingPreview || (selected ? logoFor(selected) : null);
  const list = visible.map(item => {
    const info = metadataById.get(item.id);
    const hasLogo = Boolean(info || item.logoAsset || item.logoUrl);
    return `<button type="button" class="logo-admin-item ${selected?.id === item.id ? 'selected' : ''}" data-logo-party-id="${esc(item.id)}" aria-pressed="${selected?.id === item.id}"><span class="logo-admin-item-mark">${hasLogo ? '✓' : '—'}</span><span><strong>${esc(item.officialName ?? item.name ?? '')}</strong><small>${esc(item.abbreviation || (item.entityType === 'politicalMovement' ? 'Movimento politico' : 'Sigla non documentata'))}</small></span><em>${info ? (info.verified ? 'Logo verificato' : 'Logo caricato') : item.logoVerified ? 'Ufficiale' : 'Da aggiungere'}</em></button>`;
  }).join('');
  const selectedHtml = selected ? `<section class="logo-admin-editor"><div class="logo-admin-selected"><div class="logo-admin-preview">${previewSrc ? `<img src="${esc(previewSrc)}" alt="${esc(local?.alt || selected.logoAlt || `Anteprima logo ${selected.officialName ?? selected.name ?? 'partito'}`)}" />` : '<span>Logo non disponibile</span>'}</div><div><span class="section-kicker">ID STABILE</span><code>${esc(selected.id)}</code><h2>${esc(selected.officialName ?? selected.name ?? '')}</h2><span>${selected.entityType === 'politicalMovement' ? 'Movimento politico' : selected.source === 'user' ? 'Partito creato da te' : selected.source === 'simulation' ? 'Partito demo' : 'Partito'}</span></div></div>
    <div class="logo-admin-note"><strong>Gestione locale</strong><span>I file caricati si salvano in questo browser e sono subito utilizzabili qui. GitHub Pages non può scriverli nel repository né sincronizzarli tra utenti.</span></div>
    <label class="logo-admin-upload">Carica o sostituisci SVG/PNG<input type="file" accept="image/svg+xml,image/png,.svg,.png" data-logo-upload /></label>
    <label class="logo-admin-field">Fonte del logo<input type="url" data-logo-source placeholder="https://…" value="${esc(local?.source || selected.logoSource || '')}" /></label>
    <label class="logo-admin-field">Testo alternativo<input type="text" data-logo-alt maxlength="160" value="${esc(local?.alt || selected.logoAlt || `Logo di ${selected.officialName ?? selected.name ?? 'partito'}`)}" /></label>
    <label class="logo-admin-check"><input type="checkbox" data-logo-verified ${local?.verified || (!local && selected.logoVerified) ? 'checked' : ''} /><span>Fonte verificata: logo ufficiale documentato</span></label>
    ${selected.logoSource && !local ? `<a class="catalog-source" href="${esc(selected.logoSource)}" target="_blank" rel="noopener noreferrer">Apri fonte del logo esistente ↗</a>` : ''}
    <div class="logo-admin-preview-caption" data-logo-preview-caption>${pendingPreview ? 'Anteprima temporanea. Premi “Salva nel browser” per conservarla.' : local ? 'Logo personalizzato salvato localmente.' : selected.logoVerified ? 'Logo ufficiale incluso nel repository.' : 'Nessun logo disponibile: l’archivio userà un segnaposto neutro.'}</div>
    <div class="logo-admin-actions"><button type="button" class="primary-button" data-action="logo-save" ${pendingPreview ? '' : 'disabled'}>Salva nel browser</button><button type="button" class="secondary-button" data-action="logo-delete" ${local ? '' : 'disabled'}>Elimina logo locale</button></div>
    ${error ? `<div class="wizard-errors" role="alert">${esc(error)}</div>` : ''}<p class="catalog-footnote">La casella “verificata” descrive la provenienza dichiarata per questo file. Il pannello è locale e non è un sistema di autenticazione amministrativa.</p></section>` : '<div class="catalog-empty">Nessun partito disponibile.</div>';
  return `<div class="logo-admin-backdrop" data-logo-admin-backdrop><section class="logo-admin-dialog" role="dialog" aria-modal="true" aria-labelledby="logo-admin-title"><header class="logo-admin-heading"><div><span class="section-kicker">IMPOSTAZIONI · ASSET LOCALI</span><h1 id="logo-admin-title">Gestione loghi</h1><p>Pannello amministrativo locale, senza password simulata.</p></div><button type="button" class="profile-modal-close" data-action="logo-admin-close" aria-label="Chiudi">×</button></header><div class="logo-admin-toolbar"><label class="catalog-search"><span>Cerca partito o movimento</span><input type="search" data-logo-query value="${esc(query)}" placeholder="Nome o sigla…" autocomplete="off" /></label><div><button type="button" class="secondary-button" data-action="logo-export">Esporta configurazione</button><button type="button" class="secondary-button" data-action="logo-import">Importa</button><input type="file" accept="application/json,.json" data-logo-import-file hidden /></div></div><div class="logo-admin-layout"><nav class="logo-admin-list" aria-label="Partiti e movimenti">${list || '<div class="catalog-empty">Nessun risultato.</div>'}${visible.length < matches.length ? `<button type="button" class="logo-admin-more" data-action="logo-more">Mostra altri (${matches.length-visible.length})</button>` : ''}</nav>${selectedHtml}</div></section></div>`;
}
